# Rails database configuration
development:
   adapter: mysql
   database: buckbuckgo
   username: root
   password: dtsdwarak
   host: localhost

test:
   adapter: mysql
   database: buckbuckgo
   username: root
   password: dtsdwarak
   host: localhost

production:
   adapter: mysql
   database: buckbuckgo
   username: root
   password: dtsdwarak
   host: localhost
